"""Core extraction logic for bespoke report generation.

Parses pipeline HTML reports (machine-generated by ReportBuilder) and extracts
individual sections into standalone, self-contained HTML files.

The HTML structure is predictable — generated by analysis/report.py's Jinja2
template. Section regex depends on this structure; see SECTION_RE below.
"""

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

# ── Section Parsing ──────────────────────────────────────────────────────────

# Matches <section class="report-section" id="ID">
#   <h2><span class="section-number">N.</span> Title</h2>
#   ...content...
# </section>
#
# This regex is safe because the HTML is machine-generated by our own Jinja2
# template in analysis/report.py — not arbitrary user HTML. The template
# guarantees this structure for every section.
SECTION_RE = re.compile(
    r'<section class="report-section" id="([^"]+)">\s*'
    r"<h2><span class=\"section-number\">(\d+)\.</span>\s*(.*?)</h2>"
    r"(.*?)</section>",
    re.DOTALL,
)

# Matches the <title>...</title> tag in the HTML head.
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL)

# Matches the session string from the report header meta.
SESSION_RE = re.compile(r"Session:\s*<strong>(.*?)</strong>")

# Matches the <style>...</style> block in the HTML head.
STYLE_RE = re.compile(r"<style>(.*?)</style>", re.DOTALL)

# CDN script tags to deduplicate across extracted sections.
PLOTLY_SCRIPT_RE = re.compile(
    r'<script\s+src="https://cdn\.plot\.ly/[^"]*"[^>]*>\s*</script>', re.IGNORECASE
)

# ITables / DataTables library loads (script and link tags).
DATATABLES_SCRIPT_RE = re.compile(
    r'<script\s+src="[^"]*datatables[^"]*"[^>]*>\s*</script>', re.IGNORECASE
)
DATATABLES_CSS_RE = re.compile(
    r'<link\s+[^>]*href="[^"]*datatables[^"]*"[^>]*/?\s*>', re.IGNORECASE
)


@dataclass(frozen=True)
class SectionInfo:
    """Metadata and content for one report section."""

    id: str
    number: int
    title: str
    content: str  # raw HTML between <h2> and </section>


@dataclass(frozen=True)
class ExtractedSection:
    """A section extracted from a specific source report."""

    id: str
    number: int
    title: str
    content: str
    source_report: str  # e.g., "06_irt_2d"
    source_session: str  # e.g., "91st_2025-2026"
    source_path: Path


def parse_report_css(html: str) -> str:
    """Extract the <style> block content from a report's HTML.

    Returns the CSS string, or empty string if not found.
    """
    m = STYLE_RE.search(html)
    return m.group(1) if m else ""


def parse_report_title(html: str) -> str:
    """Extract the <title> from a report's HTML."""
    m = TITLE_RE.search(html)
    return m.group(1).strip() if m else "Unknown Report"


def parse_report_session(html: str) -> str:
    """Extract the session string from a report's header meta."""
    m = SESSION_RE.search(html)
    return m.group(1).strip() if m else ""


def infer_phase_name(path: Path) -> str:
    """Infer the phase name from the report file path.

    Expects paths like .../06_irt_2d/06_irt_2d_report.html.
    Returns the directory name (e.g., "06_irt_2d").
    """
    return path.parent.name


def list_sections(html: str) -> list[SectionInfo]:
    """Parse all sections from a pipeline HTML report.

    Returns a list of SectionInfo in document order.
    """
    sections = []
    for m in SECTION_RE.finditer(html):
        sections.append(
            SectionInfo(
                id=m.group(1),
                number=int(m.group(2)),
                title=m.group(3).strip(),
                content=m.group(4),
            )
        )
    return sections


def extract_sections(
    html: str,
    selectors: list[str],
    source_path: Path,
) -> list[ExtractedSection]:
    """Extract specific sections from a report by number or ID.

    Args:
        html: Full HTML content of the source report.
        selectors: Section numbers (as strings) or section IDs.
        source_path: Path to the source report file.

    Returns:
        List of ExtractedSection in selector order.

    Raises:
        ValueError: If any selector doesn't match a section.
    """
    all_sections = list_sections(html)
    session = parse_report_session(html)
    phase = infer_phase_name(source_path)

    # Build lookup indexes.
    by_number: dict[int, SectionInfo] = {s.number: s for s in all_sections}
    by_id: dict[str, SectionInfo] = {s.id: s for s in all_sections}

    extracted = []
    for sel in selectors:
        section: SectionInfo | None = None
        if sel.isdigit():
            section = by_number.get(int(sel))
        else:
            section = by_id.get(sel)

        if section is None:
            available = ", ".join(f"{s.number} ({s.id})" for s in all_sections)
            msg = f"Section '{sel}' not found in {source_path.name}. Available: {available}"
            raise ValueError(msg)

        extracted.append(
            ExtractedSection(
                id=section.id,
                number=section.number,
                title=section.title,
                content=section.content,
                source_report=phase,
                source_session=session,
                source_path=source_path,
            )
        )

    return extracted


# ── Dependency Deduplication ─────────────────────────────────────────────────


def _collect_and_strip_dependencies(
    sections: list[ExtractedSection],
) -> tuple[list[ExtractedSection], list[str]]:
    """Remove CDN script/link tags from section content and collect unique ones.

    Returns (cleaned_sections, head_dependencies).
    """
    seen_deps: dict[str, None] = {}  # ordered set via dict
    cleaned = []

    for section in sections:
        content = section.content

        # Collect and remove Plotly scripts.
        for m in PLOTLY_SCRIPT_RE.finditer(content):
            seen_deps[m.group(0)] = None
        content = PLOTLY_SCRIPT_RE.sub("", content)

        # Collect and remove DataTables scripts.
        for m in DATATABLES_SCRIPT_RE.finditer(content):
            seen_deps[m.group(0)] = None
        content = DATATABLES_SCRIPT_RE.sub("", content)

        # Collect and remove DataTables CSS.
        for m in DATATABLES_CSS_RE.finditer(content):
            seen_deps[m.group(0)] = None
        content = DATATABLES_CSS_RE.sub("", content)

        cleaned.append(
            ExtractedSection(
                id=section.id,
                number=section.number,
                title=section.title,
                content=content,
                source_report=section.source_report,
                source_session=section.source_session,
                source_path=section.source_path,
            )
        )

    return cleaned, list(seen_deps)


# ── Rendering ────────────────────────────────────────────────────────────────


def render_extracted(
    sections: list[ExtractedSection],
    title: str | None = None,
    source_css: str = "",
) -> str:
    """Render extracted sections into a standalone HTML page.

    Args:
        sections: Sections to include, in display order.
        title: Page title. Defaults to "Extracted Report".
        source_css: CSS extracted from a source report via parse_report_css().
            If empty, uses a minimal fallback.

    Returns:
        Complete HTML string.
    """
    if not sections:
        msg = "No sections to render"
        raise ValueError(msg)

    page_title = title or "Extracted Report"
    now = datetime.now(ZoneInfo("America/Chicago")).strftime("%Y-%m-%d %H:%M %Z")

    # Deduplicate CDN dependencies.
    cleaned_sections, head_deps = _collect_and_strip_dependencies(sections)

    # Count unique source reports.
    source_reports = {(s.source_report, s.source_session) for s in cleaned_sections}
    source_count = len(source_reports)
    source_label = f"{source_count} source report{'s' if source_count > 1 else ''}"

    # Build head dependencies block.
    deps_html = "\n  ".join(head_deps) if head_deps else ""

    # Build TOC (only for multiple sections).
    toc_html = ""
    if len(cleaned_sections) > 1:
        toc_items = []
        for s in cleaned_sections:
            provenance = f" ({s.source_report})" if source_count > 1 else ""
            toc_items.append(f'    <li><a href="#{s.id}">{s.title}{provenance}</a></li>')
        toc_html = (
            '<nav class="toc">\n'
            "  <h2>Table of Contents</h2>\n"
            "  <ol>\n" + "\n".join(toc_items) + "\n  </ol>\n"
            "</nav>"
        )

    # Build sections HTML.
    sections_html_parts = []
    for s in cleaned_sections:
        provenance = ""
        if source_count > 1:
            provenance = (
                f'<p class="provenance">From {s.source_report} &mdash; {s.source_session}</p>\n    '
            )
        sections_html_parts.append(
            f'  <section class="report-section" id="{s.id}">\n'
            f"    {provenance}"
            f'<h2><span class="section-number">{s.number}.</span> {s.title}</h2>\n'
            f"    {s.content}\n"
            f"  </section>"
        )
    sections_html = "\n\n".join(sections_html_parts)

    # Provenance CSS addition.
    provenance_css = """
.provenance {
  font-size: 11px;
  color: #888;
  font-style: italic;
  margin-bottom: 4px;
  padding: 2px 8px;
  background: #f9f9f9;
  border-left: 3px solid #ddd;
}"""

    # Use source CSS if provided, otherwise minimal fallback.
    css = source_css or _FALLBACK_CSS

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{page_title}</title>
  <style>{css}{provenance_css}</style>
  {deps_html}
</head>
<body>
  <header>
    <h1>{page_title}</h1>
    <div class="meta">
      <span>Extracted: {now}</span>
      <span>From {source_label}</span>
    </div>
  </header>

  {toc_html}

  {sections_html}

  <footer>
    {page_title} &mdash; Extracted {now}
  </footer>
</body>
</html>"""


# Minimal fallback CSS when no source report CSS is available.
_FALLBACK_CSS = """\
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
  max-width: 1100px; margin: 0 auto; padding: 24px 32px;
  color: #1a1a1a; background: #ffffff; line-height: 1.5;
}
header { border-bottom: 3px solid #1a1a1a; padding-bottom: 12px; margin-bottom: 24px; }
header h1 { font-size: 24px; font-weight: 700; margin-bottom: 4px; }
header .meta { font-size: 13px; color: #555; }
header .meta span { margin-right: 16px; }
section.report-section { margin-bottom: 36px; }
section.report-section h2 {
  font-size: 18px; font-weight: 600;
  border-bottom: 2px solid #333;
  padding-bottom: 4px; margin-bottom: 16px;
}
.section-number { color: #888; font-weight: 400; margin-right: 6px; }
.figure-container { text-align: center; margin: 12px 0; }
.figure-container img { max-width: 100%; height: auto; }
footer {
  margin-top: 48px; padding-top: 12px;
  border-top: 1px solid #ccc;
  font-size: 11px; color: #888; text-align: center;
}"""


# ── Output Path ──────────────────────────────────────────────────────────────


def default_output_dir() -> Path:
    """Return the default bespoke output directory for today."""
    date_str = datetime.now(ZoneInfo("America/Chicago")).strftime("%Y-%m-%d")
    return Path("results/bespoke") / date_str


def generate_slug(title: str) -> str:
    """Generate a filesystem-safe slug from a title string."""
    slug = title.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug or "extracted"


def write_extracted(html: str, output_path: Path) -> Path:
    """Write extracted HTML to disk and update the latest symlink.

    Returns the path written.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")

    # Update latest symlink in results/bespoke/.
    bespoke_root = output_path.parent.parent
    if bespoke_root.name == "bespoke":
        latest = bespoke_root / "latest"
        if latest.is_symlink():
            latest.unlink()
        latest.symlink_to(output_path.parent.name)

    return output_path
