# Generated by Django 5.2.12 on 2026-03-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALECModelBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('category', models.CharField(default='', max_length=200)),
                ('bill_type', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=20)),
                ('url', models.URLField(default='', max_length=500)),
                ('task_force', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('is_special', models.BooleanField(default=False)),
                ('legislature_number', models.PositiveSmallIntegerField(help_text='e.g. 91 for the 91st Legislature')),
                ('name', models.CharField(help_text='Display name, e.g. "91st_2025-2026"', max_length=50)),
            ],
            options={
                'ordering': ['state', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('bill_title', models.TextField(default='')),
                ('vote_id', models.CharField(max_length=100)),
                ('vote_url', models.URLField(default='', max_length=500)),
                ('vote_datetime', models.DateTimeField(blank=True, null=True)),
                ('vote_date', models.DateField(blank=True, null=True)),
                ('chamber', models.CharField(max_length=10)),
                ('motion', models.TextField(default='')),
                ('vote_type', models.CharField(default='', max_length=100)),
                ('result', models.CharField(default='', max_length=100)),
                ('short_title', models.CharField(default='', max_length=500)),
                ('sponsor', models.CharField(default='', max_length=200)),
                ('sponsor_slugs', models.TextField(default='')),
                ('yea_count', models.PositiveSmallIntegerField(default=0)),
                ('nay_count', models.PositiveSmallIntegerField(default=0)),
                ('present_passing_count', models.PositiveSmallIntegerField(default=0)),
                ('absent_not_voting_count', models.PositiveSmallIntegerField(default=0)),
                ('not_voting_count', models.PositiveSmallIntegerField(default=0)),
                ('total_votes', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollcalls', to='legislature.session')),
            ],
            options={
                'ordering': ['session', 'vote_id'],
            },
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('chamber', models.CharField(max_length=10)),
                ('party', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=20)),
                ('member_url', models.URLField(default='', max_length=500)),
                ('ocd_id', models.CharField(default='', max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislators', to='legislature.session')),
            ],
            options={
                'ordering': ['session', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='BillText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('version', models.CharField(default='', max_length=50)),
                ('text', models.TextField()),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('source_url', models.URLField(default='', max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_texts', to='legislature.session')),
            ],
            options={
                'ordering': ['session', 'bill_number', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='BillAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50)),
                ('action_code', models.CharField(max_length=50)),
                ('chamber', models.CharField(max_length=10)),
                ('committee_names', models.TextField(default='')),
                ('occurred_datetime', models.DateTimeField(blank=True, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=200)),
                ('journal_page_number', models.CharField(default='', max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_actions', to='legislature.session')),
            ],
            options={
                'ordering': ['session', 'bill_number', 'occurred_datetime'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='legislature.state'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=50)),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislature.legislator')),
                ('rollcall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislature.rollcall')),
            ],
            options={
                'ordering': ['rollcall', 'legislator'],
            },
        ),
        migrations.AddConstraint(
            model_name='rollcall',
            constraint=models.UniqueConstraint(fields=('session', 'vote_id'), name='unique_rollcall_vote_id'),
        ),
        migrations.AddConstraint(
            model_name='legislator',
            constraint=models.UniqueConstraint(fields=('session', 'slug'), name='unique_legislator_slug'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('state', 'start_year', 'is_special'), name='unique_session'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('rollcall', 'legislator'), name='unique_vote'),
        ),
    ]
