# Generated by Django 5.2.12 on 2026-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alecmodelbill',
            name='bill_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='alecmodelbill',
            name='task_force',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='alecmodelbill',
            name='title',
            field=models.TextField(),
        ),
    ]
