# Generated by Django 5.2.12 on 2026-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0002_alter_alecmodelbill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollcall',
            name='result',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='short_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='sponsor',
            field=models.TextField(default=''),
        ),
    ]
