# Generated by Django 5.2.12 on 2026-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0003_alter_rollcall_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaction',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
