# Generated by Django 5.2.12 on 2026-03-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0005_billaction_legislature_session_520c70_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislator',
            options={'ordering': ['session', 'legislator_slug']},
        ),
        migrations.RemoveConstraint(
            model_name='legislator',
            name='unique_legislator_slug',
        ),
        migrations.RenameField(
            model_name='legislator',
            old_name='slug',
            new_name='legislator_slug',
        ),
        migrations.AddConstraint(
            model_name='legislator',
            constraint=models.UniqueConstraint(fields=('session', 'legislator_slug'), name='unique_legislator_slug'),
        ),
    ]
